apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
spec:
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:v0.21.0
      script: |
        #!/bin/sh
        /kaniko/executor --context=dir://$(resources.inputs.source.path) --dockerfile=$(resources.inputs.source.path)/Dockerfile --destination=dockernanda777/my-app:latest
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
          readOnly: true
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-secret

